title = "The Midlands Society"
baseURL = "https://60e57a3836b60b000818d5da--wizardly-torvalds-0a15bc.netlify.app/"
languageCode = "en-us"
theme = "ananke"
themesDir = "themes"
resourceDir = "resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/oxfordmidlanders"
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-red"
  featured_image = ""
  recent_posts_number = 2

[markup.goldmark.renderer]
  unsafe = true

